baseURL = "https://abundantlysocial.com"
languageCode = "en-us"
title = "Abundantly Social"

[taxonomies]
tag = "tags"
category = "categories"
videotag = "videotags"
videoseries = "videoseries"

[params]
cloudinary_url = "https://res.cloudinary.com/modii/"