baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

[taxonomies]
tag = "tags"
category = "categories"
videotag = "videotags"
videoseries = "videoseries"

[params]
cloudinary_url = "https://res.cloudinary.com/modii/"

[permalinks]
pages = "/:filename"