---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/_index.md
  label: HomePage
- type: directory
  path: content
  label: Other Pages
  create: all
  match: "*.md"
  exclude: _index.md
  new_doc_ext: md
  templates:
  - page
- type: directory
  path: content
  label: Content List Pages
  create: none
  match: "*[blog,videos,authors]/_*"
  templates:
  - list-page
- type: heading
  label: Content
- type: directory
  path: content/blog
  label: Posts
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - post
- type: directory
  path: content/videos
  label: Videos
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - video
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - author
- type: heading
  label: Other
- type: directory
  path: data
  label: Data / Settings
  create: none
  match: "**/*"
  exclude: "**/*.toml"
  new_doc_ext: yaml
  templates:
  - menus
  - style
  - settings
  - blank
upload_dir: abundantlysocial
public_path: https://res.cloudinary.com/modii/w_840,q_50,f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.47.1
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.47.1
