---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/_index.md
  label: HomePage
- type: directory
  path: content
  label: Other Pages
  create: all
  match: "*.md"
  exclude: _index.md
  new_doc_ext: md
  templates:
  - page
- type: directory
  path: content
  label: Content List Pages
  create: none
  match: "*[blog,videos,authors]/_*"
  templates:
  - list-page
- type: heading
  label: Content
- type: directory
  path: content/blog
  label: Posts
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - post
- type: directory
  path: content/videos
  label: Videos
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - video
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
  exclude: "**/_index.md"
  templates:
  - author
- type: heading
  label: Data / Settings
- type: document
  path: data/settings.yaml
  label: General Settings
  templates:
  - settings
- type: document
  path: data/style.yaml
  label: Appearance / Style
  templates:
  - blank
- type: document
  path: data/menus.yaml
  label: Menus
  templates:
  - menus
- type: document
  path: data/icons.yaml
  label: Icons
  read_only: true
  templates:
  - blank
upload_dir: abundantlysocial
public_path: https://res.cloudinary.com/modii/w_840,q_50,f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: 0.47.1
