---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/_index.md
  label: HomePage
- type: directory
  path: content
  label: Content List Pages
  create: none
  match: "*[blog,videos,authors]/_*"
- type: directory
  path: content
  label: Other Pages
  create: all
  match: "[!_]*.md"
  new_doc_ext: md
  templates:
  - page
- type: heading
  label: Content
- type: directory
  path: content/blog
  label: Posts
  create: all
  match: "**/[!_]*"
  templates:
  - post
- type: directory
  path: content/videos
  label: Videos
  create: all
  match: "**/[!_]*"
  templates:
  - video
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/[!_]*"
  templates:
  - author
upload_dir: abundantlysocial
public_path: https://res.cloudinary.com/modii/w_840,q_50,f_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
version: 0.47.1
